version: '3'
services:
  php:
    container_name: js_php
    build:
        context: "./docker/php"
        dockerfile: "Dockerfile"    
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html
    networks:
     - js

networks:
  js:
    driver: "bridge"
